# Generated by Django 5.2.14 on 2026-06-10 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("new_signups", models.PositiveIntegerField(default=0)),
                ("most_viewed_page", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "analytics_dailystats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_url", models.CharField(max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_pageviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_p_created_1c73f5_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_p_user_id_f2d56e_idx",
                    ),
                    models.Index(
                        fields=["page_url"], name="analytics_p_page_ur_afa8aa_idx"
                    ),
                ],
            },
        ),
    ]
