# Generated by Django 5.2.14 on 2026-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Leave blank for no expiry", null=True
            ),
        ),
    ]
