# Generated by Django 5.2.14 on 2026-07-01 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("difficulty", models.CharField(default="beginner", max_length=20)),
                ("topic", models.CharField(max_length=50)),
                ("starter_code", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("points", models.PositiveIntegerField(default=10)),
                ("date", models.DateField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "daily_challenges",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.TextField()),
                ("score", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.dailychallenge",
                    ),
                ),
            ],
            options={
                "db_table": "daily_challenge_submissions",
                "unique_together": {("user", "challenge")},
            },
        ),
    ]
