# Generated by Django 5.2.14 on 2026-06-11 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("video", "Video Link"),
                            ("code", "Source Code"),
                            ("slides", "Presentation Slides"),
                            ("exercise", "Exercise File"),
                            ("cheatsheet", "Cheat Sheet"),
                            ("other", "Other"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube or video link"),
                ),
                ("external_link", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "course_materials",
                "ordering": ["-created_at"],
            },
        ),
    ]
