# Generated by Django 6.0.5 on 2026-05-07 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('html_template', models.TextField(blank=True)),
                ('css_template', models.TextField(blank=True)),
                ('js_template', models.TextField(blank=True)),
                ('html_solution', models.TextField(blank=True)),
                ('css_solution', models.TextField(blank=True)),
                ('js_solution', models.TextField(blank=True)),
                ('tests', models.JSONField(default=list)),
                ('hints', models.JSONField(default=list)),
                ('difficulty', models.PositiveIntegerField(default=1, help_text='1-5')),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'code_challenges',
                'ordering': ['order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='playground_templates/')),
                ('html_code', models.TextField(blank=True, default='')),
                ('css_code', models.TextField(blank=True, default='')),
                ('js_code', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'playground_templates',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('html_code', models.TextField(blank=True)),
                ('css_code', models.TextField(blank=True)),
                ('js_code', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='playground.codechallenge')),
            ],
            options={
                'db_table': 'challenge_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('html_code', models.TextField(blank=True, default='')),
                ('css_code', models.TextField(blank=True, default='')),
                ('js_code', models.TextField(blank=True, default='')),
                ('css_libraries', models.JSONField(blank=True, default=list, help_text="ex: ['bootstrap', 'tailwind']")),
                ('js_libraries', models.JSONField(blank=True, default=list, help_text="ex: ['react', 'vue']")),
                ('viewport_width', models.PositiveIntegerField(default=1440)),
                ('viewport_height', models.PositiveIntegerField(default=900)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('fork_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playground_snippets',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='playground__user_id_d2191b_idx'), models.Index(fields=['is_public', '-view_count'], name='playground__is_publ_5b61e7_idx')],
            },
        ),
    ]
