# Generated by Django 5.2.14 on 2026-07-02 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords that trigger this response",
                        max_length=500,
                    ),
                ),
                (
                    "question_pattern",
                    models.TextField(help_text="Example questions this matches"),
                ),
                ("response", models.TextField(help_text="The bot's response")),
                (
                    "priority",
                    models.IntegerField(default=1, help_text="Higher = checked first"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_knowledge",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
