# Generated by Django 5.2.14 on 2026-05-29 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_sessions", models.PositiveIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mentorship_availability",
                "ordering": ["day", "start_time"],
            },
        ),
        migrations.RenameField(
            model_name="mentorshipsession",
            old_name="notes",
            new_name="admin_notes",
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="codereview",
            name="code_link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
